# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dado_sexy.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Sexy(object):
    def setupUi(self, Sexy):
        Sexy.setObjectName("Sexy")
        Sexy.resize(500, 500)
        Sexy.setMinimumSize(QtCore.QSize(500, 500))
        Sexy.setMaximumSize(QtCore.QSize(500, 500))
        Sexy.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.verticalLayout = QtWidgets.QVBoxLayout(Sexy)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(Sexy)
        self.frame.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.imgbnt = QtWidgets.QToolButton(self.frame)
        self.imgbnt.setMinimumSize(QtCore.QSize(464, 464))
        self.imgbnt.setMaximumSize(QtCore.QSize(16777212, 16777215))
        self.imgbnt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.imgbnt.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.imgbnt.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Img/inicio.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.imgbnt.setIcon(icon)
        self.imgbnt.setIconSize(QtCore.QSize(464, 464))
        self.imgbnt.setCheckable(False)
        self.imgbnt.setAutoRepeat(False)
        self.imgbnt.setAutoExclusive(False)
        self.imgbnt.setAutoRaise(True)
        self.imgbnt.setObjectName("imgbnt")
        self.horizontalLayout_3.addWidget(self.imgbnt)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(Sexy)
        QtCore.QMetaObject.connectSlotsByName(Sexy)

    def retranslateUi(self, Sexy):
        _translate = QtCore.QCoreApplication.translate
        Sexy.setWindowTitle(_translate("Sexy", "DADO SEXY"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Sexy = QtWidgets.QWidget()
    ui = Ui_Sexy()
    ui.setupUi(Sexy)
    Sexy.show()
    sys.exit(app.exec_())
